# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170911_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments_articles',
            new_name='comments_article',
        ),
    ]
