# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170911_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Комментарии'),
        ),
    ]
